Dodo: Bump Publish Workflow Python Version to 3.8
**Problem**
Dodo workflow fails with https://github.com/twitter/dodo/actions/runs/8930806565/job/24531647607
```
Run actions/setup-python@v2
Version 3.6 was not found in the local cache
Error: Version 3.6 with arch x64 not found
```
**Solution**
Choose 3.8 which is available in the list of versions https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json

Differential Revision: https://phabricator.twitter.biz/D1141083